### ISSUE TITLE
Absolute dropdown items not reachable

### ISSUE THREAD

**Issue by matteofrana** [dej611/spid-react-button#87]
I am using the React SPID button in a Next.js 12 project.
I show the modal version for lower resolutions and the dropdown version on higher screen size, where you can see the problem.
When the button is placed in the lower part of the screen, the absolute dropdown doesn't push the page content down and so some of the IDPs are hidden and not reachable.

You can see an example here, with a screen height of about 600px:
https://spid.retteweb.eu/?comune=bergamo&servizio=iscrizioni

While on a site like this:
https://serviziweb2.inps.it/PassiWeb/jsp/spid/loginSPID.jsp
you see that, when the dropdown appears, the page height increase, so that it scrolls.

Thank you,
Matteo

**Comment by dej611** [comment]
Can confirm the issue. I'll need to sort out a way to keep the accessibility feature while making the content scrollable.

> While on a site like this:
serviziweb2.inps.it/PassiWeb/jsp/spid/loginSPID.jsp
you see that, when the dropdown appears, the page height increase, so that it scrolls.

I can see that the page is still scrollable, but the implementation there does not take into account accessibility.
If you open the dropdown and use only the keyboard, the focus will go out of the content when it reaches the bottom rather than loop at the top of the dropdown as it should to be compliant.

**Comment by matteofrana** [comment]
Hi @dej611, I see you created a PR 2 days ago. 
When do you think you will be able to merge it and publish a new version on npm?

Thank you,
Matteo

**Comment by dej611** [comment]
Published. Should be available in few minutes on npm.
